(()=>{'use strict';
const TAU=2*Math.PI,AU_M=149597870700,DAY_S=86400,MU_SUN=1.32712440018e20;
const bodies={earth:{name:'지구',a:1.00000011,e:.01671022,period:365.256,color:'#70e1c3'},mercury:{name:'수성',a:.38709893,e:.20563069,period:87.9691,color:'#d8b08c'},mars:{name:'화성',a:1.52366231,e:.09341233,period:686.98,color:'#ff8c6b'},halley:{name:'1P/Halley',a:17.834,e:.96714,period:27759,color:'#8ab9ff'},custom:{name:'사용자 정의',a:1,e:.5,period:365.256,color:'#70e1c3'}};
const $=id=>document.getElementById(id),clamp=(x,a,b)=>Math.min(b,Math.max(a,x)),modTau=x=>((x%TAU)+TAU)%TAU;
const fmt=(x,d=6)=>!Number.isFinite(x)?'—':((Math.abs(x)!==0&&Math.abs(x)<1e-5)||Math.abs(x)>=1e6?x.toExponential(3):x.toFixed(d));
function initialGuess(M,e,s){M=modTau(M);if(s==='mean')return M;if(s==='pi')return Math.PI;if(s==='offset'){const sm=M>Math.PI?M-TAU:M;return modTau(sm+(Math.sign(Math.sin(sm))||1)*.85*e)}return e<.8?M:Math.PI}
function solveKepler(M,e,o={}){const tol=o.tol??1e-12,maxIter=o.maxIter??30,strategy=o.strategy??'adaptive',fallback=o.fallback??true,trace=o.trace??false;if(!(e>=0&&e<1))return{converged:false,reason:'0≤e<1 필요',rows:[]};const m=modTau(M);let E=initialGuess(m,e,strategy),rows=[],converged=false,usedFallback=false;for(let n=0;n<maxIter;n++){const f=E-e*Math.sin(E)-m,fp=1-e*Math.cos(E);if(!Number.isFinite(f)||!Number.isFinite(fp)||Math.abs(fp)<1e-15)break;const delta=-f/fp;if(trace)rows.push({n,E,residual:f,delta,method:'Newton'});const next=E+delta,nr=next-e*Math.sin(next)-m;E=next;if(Math.abs(delta)<tol&&Math.abs(nr)<tol){converged=true;break}}
if(!converged&&fallback){usedFallback=true;if(Math.abs(m)<tol){E=0;converged=true}else{let lo=0,hi=TAU;for(let k=0;k<80;k++){const mid=.5*(lo+hi),fm=mid-e*Math.sin(mid)-m;if(trace)rows.push({n:rows.length,E:mid,residual:fm,delta:.5*(hi-lo),method:'Bisection'});E=mid;if(Math.abs(fm)<tol||Math.abs(hi-lo)<tol){converged=true;break}if(fm>0)hi=mid;else lo=mid}}}
E=modTau(E);const residual=Math.min(Math.abs(E-e*Math.sin(E)-m),Math.abs((E-TAU)-e*Math.sin(E-TAU)-m));return{E,M:m,residual,converged:converged||residual<tol*10,usedFallback,rows,iterationCount:rows.filter(r=>r.method==='Newton').length,totalSteps:rows.length,strategy}}
function orbitalState(body,tDays,o={}){const M=modTau(TAU*tDays/body.period),sol=solveKepler(M,body.e,{tol:o.tol??1e-12,maxIter:o.maxIter??30,strategy:o.strategy??'adaptive',fallback:true,trace:false}),E=sol.E,a=body.a,e=body.e,x=a*(Math.cos(E)-e),y=a*Math.sqrt(1-e*e)*Math.sin(E),r=a*(1-e*Math.cos(E));let nu=modTau(2*Math.atan2(Math.sqrt(1+e)*Math.sin(E/2),Math.sqrt(1-e)*Math.cos(E/2)));const r2=a*(1-e*e)/(1+e*Math.cos(nu)),x2=r2*Math.cos(nu),y2=r2*Math.sin(nu),coordError=Math.hypot(x-x2,y-y2),mu=MU_SUN*(body.centralMass??1),aM=a*AU_M,nMotion=Math.sqrt(mu/aM**3),dEdt=nMotion/(1-e*Math.cos(E)),vx=-aM*Math.sin(E)*dEdt,vy=aM*Math.sqrt(1-e*e)*Math.cos(E)*dEdt,speed=Math.hypot(vx,vy),specificEnergy=.5*speed*speed-mu/(r*AU_M),specificAngularMomentum=x*AU_M*vy-y*AU_M*vx;return{...sol,M,E,nu,r,x,y,x2,y2,coordError,vx,vy,speed,specificEnergy,specificAngularMomentum}}
function setupCanvas(canvas){const ratio=Math.max(1,devicePixelRatio||1),w=canvas.clientWidth||canvas.width,h=canvas.clientHeight||canvas.height;if(canvas.width!==Math.floor(w*ratio)||canvas.height!==Math.floor(h*ratio)){canvas.width=Math.floor(w*ratio);canvas.height=Math.floor(h*ratio)}const ctx=canvas.getContext('2d');ctx.setTransform(ratio,0,0,ratio,0,0);return{ctx,w,h}}
function colors(){const l=document.body.classList.contains('light');return{bg:l?'#f7fbfc':'#07131d',grid:l?'rgba(27,76,99,.12)':'rgba(142,190,218,.10)',text:l?'#526a77':'#91a7b9',line:l?'#406b80':'#4d7289',accent:'#70e1c3',accent2:'#74a9ff',warning:'#ffcb6b',danger:'#ff7b8a'}}
function clear(ctx,w,h,bg){ctx.clearRect(0,0,w,h);ctx.fillStyle=bg;ctx.fillRect(0,0,w,h)}
function grid(ctx,w,h,color){ctx.save();ctx.strokeStyle=color;ctx.lineWidth=1;for(let x=0;x<w;x+=50){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,h);ctx.stroke()}for(let y=0;y<h;y+=50){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(w,y);ctx.stroke()}ctx.restore()}
function arrow(ctx,x1,y1,x2,y2,color){const a=Math.atan2(y2-y1,x2-x1),head=8;ctx.save();ctx.strokeStyle=ctx.fillStyle=color;ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(x1,y1);ctx.lineTo(x2,y2);ctx.stroke();ctx.beginPath();ctx.moveTo(x2,y2);ctx.lineTo(x2-head*Math.cos(a-Math.PI/6),y2-head*Math.sin(a-Math.PI/6));ctx.lineTo(x2-head*Math.cos(a+Math.PI/6),y2-head*Math.sin(a+Math.PI/6));ctx.closePath();ctx.fill();ctx.restore()}
function lineChart(canvas,values,o={}){const{ctx,w,h}=setupCanvas(canvas),c=colors();clear(ctx,w,h,c.bg);grid(ctx,w,h,c.grid);const pad={l:54,r:18,t:18,b:36},arr=values.filter(Number.isFinite);if(!arr.length)return;let min=o.minY??Math.min(...arr),max=o.maxY??Math.max(...arr);if(Math.abs(max-min)<1e-20){max+=1;min-=1}const sx=(w-pad.l-pad.r)/Math.max(1,values.length-1),sy=(h-pad.t-pad.b)/(max-min);ctx.strokeStyle=o.color??c.accent;ctx.lineWidth=2;ctx.beginPath();values.forEach((v,i)=>{const x=pad.l+i*sx,y=h-pad.b-(v-min)*sy;i?ctx.lineTo(x,y):ctx.moveTo(x,y)});ctx.stroke();ctx.fillStyle=c.text;ctx.font='11px system-ui';ctx.textAlign='right';ctx.fillText(max.toExponential(2),pad.l-8,pad.t+4);ctx.fillText(min.toExponential(2),pad.l-8,h-pad.b);ctx.textAlign='center';ctx.fillText(o.xLabel??'sample',(pad.l+w-pad.r)/2,h-10)}
let selectedKey='earth',currentBody={...bodies.earth,centralMass:1},currentTime=0,playing=false,lastFrame=performance.now(),validationRows=[];
function readBody(){const a=+$('semiMajorInput').value,e=+$('eccInput').value,period=+$('periodInput').value,centralMass=+$('centralMassInput').value,valid=a>0&&period>0&&centralMass>0&&e>=0&&e<1;$('orbitStatus').textContent=valid?'정상':'입력 오류';$('orbitStatus').className=`status-badge ${valid?'ok':'bad'}`;return valid?{...bodies[selectedKey],a,e,period,centralMass,name:selectedKey==='custom'?'사용자 정의':bodies[selectedKey].name}:null}
function applyBody(key){selectedKey=key;const b=bodies[key];$('semiMajorInput').value=b.a;$('eccInput').value=b.e;$('periodInput').value=b.period;$('centralMassInput').value=1;['semiMajorInput','eccInput','periodInput'].forEach(id=>$(id).disabled=key!=='custom');currentBody={...b,centralMass:1};currentTime=0;$('timeSlider').value=0;$('orbitTitle').textContent=`${b.name}의 이상적 2체 궤도`;updateOrbit()}
function mapOrbit(x,y,b,w,h){const semiMinor=b.a*Math.sqrt(1-b.e*b.e),m=60,s=Math.min((w-2*m)/(2*b.a),(h-2*m)/(2*semiMinor||1)),cx=w/2,cy=h/2;return[cx+x*s,cy-y*s,s,cx,cy]}
function drawOrbit(){const{ctx,w,h}=setupCanvas($('orbitCanvas')),c=colors();clear(ctx,w,h,c.bg);grid(ctx,w,h,c.grid);const b=currentBody;if(!b)return;const s=orbitalState(b,currentTime),[sx,sy,scale,cx,cy]=mapOrbit(s.x,s.y,b,w,h);ctx.strokeStyle=c.line;ctx.lineWidth=1.6;ctx.beginPath();for(let i=0;i<=720;i++){const E=TAU*i/720,x=b.a*(Math.cos(E)-b.e),y=b.a*Math.sqrt(1-b.e*b.e)*Math.sin(E),p=mapOrbit(x,y,b,w,h);i?ctx.lineTo(p[0],p[1]):ctx.moveTo(p[0],p[1])}ctx.stroke();if($('showArea').checked){const seg=12,dt=b.period/seg;ctx.fillStyle='rgba(112,225,195,.07)';ctx.strokeStyle='rgba(112,225,195,.25)';for(let k=0;k<seg;k++){const a0=orbitalState(b,k*dt),a1=orbitalState(b,(k+1)*dt),p0=mapOrbit(a0.x,a0.y,b,w,h),p1=mapOrbit(a1.x,a1.y,b,w,h);ctx.beginPath();ctx.moveTo(cx,cy);ctx.lineTo(p0[0],p0[1]);ctx.lineTo(p1[0],p1[1]);ctx.closePath();ctx.fill();ctx.stroke()}}ctx.shadowColor='#ffca65';ctx.shadowBlur=18;ctx.fillStyle='#ffca65';ctx.beginPath();ctx.arc(cx,cy,9,0,TAU);ctx.fill();ctx.shadowBlur=0;ctx.strokeStyle='rgba(116,169,255,.55)';ctx.beginPath();ctx.moveTo(cx,cy);ctx.lineTo(sx,sy);ctx.stroke();if($('showVelocity').checked){const vs=55/Math.max(1,s.speed/1000);arrow(ctx,sx,sy,sx+s.vx/1000*vs,sy-s.vy/1000*vs,c.warning)}ctx.shadowColor=b.color;ctx.shadowBlur=16;ctx.fillStyle=b.color;ctx.beginPath();ctx.arc(sx,sy,7,0,TAU);ctx.fill();ctx.shadowBlur=0;ctx.fillStyle=c.text;ctx.font='12px system-ui';ctx.fillText('초점',cx+13,cy-12);ctx.fillText(b.name,sx+12,sy-10);updateMetrics(s)}
function updateMetrics(s){$('metricM').textContent=fmt(s.M,5);$('metricE').textContent=fmt(s.E,5);$('metricNu').textContent=fmt(s.nu,5);$('metricR').textContent=fmt(s.r,5);$('metricV').textContent=fmt(s.speed/1000,3);$('metricIterations').textContent=s.iterationCount;$('metricResidual').textContent=fmt(s.residual,3);$('metricCoordError').textContent=fmt(s.coordError,3);$('timeLabel').textContent=`${fmt(currentTime,2)} day`}
function updateOrbit(){const b=readBody();if(!b)return;currentBody=b;currentTime=+$('timeSlider').value/1000*b.period;drawOrbit()}
function animate(now){const dt=Math.min(80,now-lastFrame);lastFrame=now;if(playing&&currentBody){currentTime=(currentTime+dt/1000*currentBody.period/18*+$('speedSelect').value)%currentBody.period;$('timeSlider').value=Math.round(currentTime/currentBody.period*1000);drawOrbit()}requestAnimationFrame(animate)}
function runSolver(){const e=+$('solverE').value,M=+$('solverM').value,r=solveKepler(M,e,{tol:+$('toleranceSelect').value,maxIter:+$('maxIterInput').value,strategy:$('initialStrategy').value,fallback:$('fallbackCheck').checked,trace:true});$('solverStatus').textContent=r.converged?(r.usedFallback?'fallback 수렴':'Newton 수렴'):'실패';$('solverStatus').className=`status-badge ${r.converged?'ok':'bad'}`;$('solverSummary').textContent=`E=${fmt(r.E,12)} · 잔차=${fmt(r.residual,3)} · 총 ${r.totalSteps}단계`;$('iterationBody').innerHTML=r.rows.map(q=>`<tr><td>${q.n}</td><td>${fmt(q.E,12)}</td><td>${fmt(q.residual,4)}</td><td>${fmt(q.delta,4)}</td><td>${q.method}</td></tr>`).join('');lineChart($('residualCanvas'),r.rows.map(q=>Math.log10(Math.max(Math.abs(q.residual),1e-16))),{xLabel:'iteration n',color:colors().accent2})}
function validateBody(b,N){const rows=[];for(let i=0;i<=N;i++)rows.push({i,t:b.period*i/N,...orbitalState(b,b.period*i/N)});const area=[];for(let i=0;i<N;i++){const a=rows[i],d=rows[i+1];area.push(.5*Math.abs(a.x*d.y-a.y*d.x)/(d.t-a.t))}const energies=rows.slice(0,N).map(r=>r.specificEnergy),momenta=rows.slice(0,N).map(r=>r.specificAngularMomentum),mean=area.reduce((a,b)=>a+b,0)/area.length,sd=Math.sqrt(area.reduce((a,b)=>a+(b-mean)**2,0)/area.length),mu=MU_SUN*b.centralMass,refE=-mu/(2*b.a*AU_M),refH=Math.sqrt(mu*b.a*AU_M*(1-b.e*b.e)),er=energies.map(v=>(v-refE)/Math.abs(refE)),hr=momenta.map(v=>(v-refH)/Math.abs(refH)),pred=TAU*Math.sqrt((b.a*AU_M)**3/mu)/DAY_S;return{rows,areaRates:area,energyRel:er,hRel:hr,areaCv:sd/Math.abs(mean),maxEnergyError:Math.max(...er.map(Math.abs)),maxMomentumError:Math.max(...hr.map(Math.abs)),predictedPeriod:pred,periodError:Math.abs(pred-b.period)/pred}}
function runValidation(){const N=+$('sampleCount').value,r=validateBody(currentBody,N);validationRows=r.rows.slice(0,N).map((q,i)=>({t_day:q.t,M_rad:q.M,E_rad:q.E,nu_rad:q.nu,r_AU:q.r,x_AU:q.x,y_AU:q.y,speed_km_s:q.speed/1000,kepler_residual:q.residual,area_rate_AU2_day:r.areaRates[i],energy_rel_error:r.energyRel[i],angular_momentum_rel_error:r.hRel[i]}));$('areaCv').textContent=r.areaCv.toExponential(3);$('energyError').textContent=r.maxEnergyError.toExponential(3);$('momentumError').textContent=r.maxMomentumError.toExponential(3);$('periodError').textContent=r.periodError.toExponential(3);const ma=r.areaRates.reduce((a,b)=>a+b,0)/r.areaRates.length;lineChart($('areaChart'),r.areaRates.map(v=>v/ma-1),{xLabel:'time segment',color:colors().accent});lineChart($('energyChart'),r.energyRel,{xLabel:'time sample',color:colors().accent2});lineChart($('momentumChart'),r.hRel,{xLabel:'time sample',color:colors().warning});const Ns=[30,60,120,240,480,960,1920],cvs=Ns.map(n=>Math.log10(validateBody(currentBody,n).areaCv));lineChart($('convergenceChart'),cvs,{xLabel:'log10 CV, N=30→1920',color:colors().danger})}
function downloadCSV(){if(!validationRows.length)runValidation();const h=Object.keys(validationRows[0]),lines=[h.join(',')];validationRows.forEach(r=>lines.push(h.map(k=>r[k]).join(',')));const blob=new Blob([lines.join('\n')],{type:'text/csv;charset=utf-8'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`kepler_validation_${selectedKey}.csv`;a.click();URL.revokeObjectURL(url)}
const strategies=['mean','pi','adaptive','offset'],names={mean:'E₀=M',pi:'E₀=π',adaptive:'조건부',offset:'부호 보정'};
function analyzeStrategy(strategy,rowsN=46,colsN=72){let sum=0,max=0,fallbackCount=0,failures=0;const grid=[];for(let i=0;i<rowsN;i++){const e=.99*i/(rowsN-1),row=[];for(let j=0;j<colsN;j++){const M=TAU*j/colsN,r=solveKepler(M,e,{tol:1e-12,maxIter:20,strategy,fallback:true,trace:true}),count=r.iterationCount+(r.usedFallback?10:0);row.push({count,raw:r.iterationCount,fallback:r.usedFallback,converged:r.converged});sum+=r.iterationCount;max=Math.max(max,r.iterationCount);fallbackCount+=r.usedFallback?1:0;failures+=r.converged?0:1}grid.push(row)}return{grid,average:sum/(rowsN*colsN),max,fallbackCount,failures,rowsN,colsN}}
function drawHeatmap(r){const{ctx,w,h}=setupCanvas($('heatmapCanvas')),c=colors(),p={l:54,r:18,t:18,b:42};clear(ctx,w,h,c.bg);const cw=(w-p.l-p.r)/r.colsN,ch=(h-p.t-p.b)/r.rowsN,max=Math.max(...r.grid.flat().map(d=>d.count));r.grid.forEach((row,i)=>row.forEach((d,j)=>{const t=clamp(d.count/Math.max(1,max),0,1);ctx.fillStyle=d.fallback?'#ff7182':t<.45?`rgb(${24+45*t},${59+170*t},${82+140*t})`:`rgb(${90+165*t},${170+70*(1-t)},${150-60*t})`;ctx.fillRect(p.l+j*cw,p.t+(r.rowsN-1-i)*ch,cw+.4,ch+.4)}));ctx.fillStyle=c.text;ctx.font='11px system-ui';ctx.textAlign='center';ctx.fillText('평균근점이각 M (0 → 2π)',(p.l+w-p.r)/2,h-11);ctx.save();ctx.translate(13,(p.t+h-p.b)/2);ctx.rotate(-Math.PI/2);ctx.fillText('이심률 e (0 → 0.99)',0,0);ctx.restore();$('heatmapSummary').textContent=`평균 ${r.average.toFixed(2)}회 · 최대 ${r.max}회 · fallback ${r.fallbackCount}점`}
function runAnalysis(){$('heatmapSummary').textContent='계산 중…';requestAnimationFrame(()=>{drawHeatmap(analyzeStrategy($('heatmapStrategy').value));$('strategyComparisonBody').innerHTML=strategies.map(s=>({s,...analyzeStrategy(s,28,48)})).map(r=>`<tr><td>${names[r.s]}</td><td>${r.average.toFixed(2)}</td><td>${r.max}</td><td>${r.fallbackCount}</td></tr>`).join('')})}
function activate(name){document.querySelectorAll('.tab').forEach(b=>b.classList.toggle('active',b.dataset.tab===name));document.querySelectorAll('.panel').forEach(p=>p.classList.remove('active'));$(`${name}Panel`).classList.add('active');setTimeout(()=>{if(name==='orbit')drawOrbit();if(name==='solver')runSolver();if(name==='validation')runValidation();if(name==='analysis')runAnalysis()},30)}
document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>activate(b.dataset.tab));$('bodySelect').onchange=e=>applyBody(e.target.value);['semiMajorInput','eccInput','periodInput','centralMassInput','timeSlider','showArea','showVelocity'].forEach(id=>$(id).addEventListener('input',updateOrbit));$('playBtn').onclick=()=>{playing=!playing;$('playBtn').textContent=playing?'❚❚ 정지':'▶ 재생'};$('resetBtn').onclick=()=>{currentTime=0;$('timeSlider').value=0;drawOrbit()};$('solverE').oninput=()=>{$('solverEOut').textContent=(+$('solverE').value).toFixed(3)};$('solverM').oninput=()=>{$('solverMOut').textContent=`${(+$('solverM').value).toFixed(3)} rad`};$('solveBtn').onclick=runSolver;$('runValidationBtn').onclick=runValidation;$('downloadCsvBtn').onclick=downloadCSV;$('runAnalysisBtn').onclick=runAnalysis;$('themeToggle').onclick=()=>{document.body.classList.toggle('light');drawOrbit();runSolver()};addEventListener('resize',()=>{drawOrbit();if($('validationPanel').classList.contains('active'))runValidation()});applyBody('earth');runSolver();requestAnimationFrame(animate);window.KeplerLab={solveKepler,orbitalState,validateBody,bodies,constants:{TAU,AU_M,DAY_S,MU_SUN}}})();
